repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus
    namespace: observability
    chart: prometheus-community/kube-prometheus-stack
    disableValidationOnInstall: true

helmDefaults:
  timeout: 900
  wait: true
  force: true
  atomic: true
  cleanupOnFail: true
  kubeContext: docker-desktop
